import { createElement } from 'lwc';
//import LinkWithOrgDataWire3 from 'c/linkWithOrgDataWire3';
import linkWithOrgDataCrtUpdRcd from 'c/linkWithOrgDataCrtUpdRcd';

describe('c-link-with-org-data-crt-upd-rcd', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-link-with-org-data-crt-upd-rcd', {
            is: linkWithOrgDataCrtUpdRcd
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});